# Generated by Django 4.1.4 on 2023-01-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinEventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_current_date', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(default='', max_length=500)),
                ('country', models.CharField(default='', max_length=10)),
                ('event_time', models.CharField(default='', max_length=10)),
                ('event_date', models.CharField(default='', max_length=10)),
                ('event_subject', models.CharField(default='', max_length=100)),
                ('event_mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_date', to='analysis.fineventdate')),
            ],
        ),
    ]
