# Generated by Django 4.1.4 on 2023-01-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='forecast',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='financialevent',
            name='previous',
            field=models.CharField(default='', max_length=10),
        ),
    ]
