# Generated by Django 4.1.5 on 2023-01-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_finnews"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=10)),
                ("in_korean", models.CharField(max_length=10)),
                ("current", models.FloatField(blank=True, default=0)),
                ("day_before", models.FloatField(blank=True, default=0)),
                ("change", models.FloatField(blank=True, default=0)),
                ("buy", models.FloatField(blank=True, default=0)),
                ("sell", models.FloatField(blank=True, default=0)),
                ("send", models.FloatField(blank=True, default=0)),
                ("receive", models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name="StockCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(default="", max_length=5)),
                ("company_name", models.CharField(default="", max_length=20)),
                ("industry", models.CharField(default="", max_length=20)),
                ("market_cap", models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CompanyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=10)),
                ("open_price", models.FloatField(blank=True, default=0)),
                ("high_price", models.FloatField(blank=True, default=0)),
                ("low_price", models.FloatField(blank=True, default=0)),
                ("close_price", models.FloatField(blank=True, default=0)),
                ("adj_close_price", models.FloatField(blank=True, default=0)),
                ("volume", models.FloatField(blank=True, default=0)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_ticker",
                        to="analysis.stockcompany",
                    ),
                ),
            ],
        ),
    ]
