# Generated by Django 4.1.5 on 2023-01-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_currency_stockcompany_companyprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockcompany",
            name="recommandtion",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
    ]
