# Generated by Django 4.1.5 on 2023-01-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0006_stockindex"),
    ]

    operations = [
        migrations.DeleteModel(name="StockIndex",),
    ]
