# Generated by Django 4.1.5 on 2023-01-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0008_mailingticker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingticker",
            name="ticker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing_ticker",
                to="analysis.stockcompany",
            ),
        ),
    ]
