# Generated by Django 4.1.5 on 2023-01-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0011_mailingticker_company_alter_mailingticker_ticker"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockcompany",
            name="last_price",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
