# Generated by Django 4.1.5 on 2023-01-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0012_stockcompany_last_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockcompany",
            name="WeekChange",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="beta",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="bookValue",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="currentRatio",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="debtToEquity",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="earningsGrowth",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="earningsQuarterlyGrowth",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="ebitda",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="ebitdaMargins",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="enterpriseToEbitda",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="enterpriseToRevenue",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="enterpriseValue",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="fiftyDayAverage",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="floatShares",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="forwardEps",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="forwardPE",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="freeCashflow",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="grossMargins",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="grossProfits",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="heldPercentInsiders",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="heldPercentInstitutions",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="lastDividendValue",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="netIncomeToCommon",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="operatingCashflow",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="operatingMargins",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="payoutRatio",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="pegRatio",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="priceToBook",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="priceToSalesTrailing12Months",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="profitMargins",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="quickRatio",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="regularMarketDayHigh",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="regularMarketOpen",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="returnOnAssets",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="returnOnEquity",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="revenueGrowth",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="revenuePerShare",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="sector",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="sharesOutstanding",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="sharesPercentSharesOut",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="sharesShort",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="sharesShortPriorMonth",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="shortPercentOfFloat",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="shortRatio",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="targetHighPrice",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="targetLowPrice",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="targetMedianPrice",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="target_mean_price",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="totalCash",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="totalCashPerShare",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="totalDebt",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="totalRevenue",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="trailingEps",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="stockcompany",
            name="twoHundredDayAverage",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="stockcompany",
            name="industry",
            field=models.CharField(default="", max_length=50),
        ),
    ]
