# Generated by Django 4.1.5 on 2023-01-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0014_sendmail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockcompany",
            name="lastDividendValue",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
