# Generated by Django 4.1.4 on 2023-01-16 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('port_history', models.TextField(blank=True, default='', null=True)),
                ('monthly_return', models.TextField(blank=True, default='', null=True)),
                ('port_value', models.FloatField(default=0, null=True)),
                ('weight', models.IntegerField(default=0, null=True)),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('money', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('buy_price', models.FloatField(default=0.0)),
                ('sell_price', models.FloatField(default=0.0)),
                ('buy_date', models.DateField(blank=True, null=True)),
                ('sell_date', models.DateField(blank=True, null=True)),
                ('profit', models.FloatField(default=0.0)),
                ('trans_portfolio', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_port', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('buy_price', models.FloatField(default=0.0)),
                ('sell_price', models.FloatField(default=0.0)),
                ('current_price', models.FloatField(default=0, null=True)),
                ('target_price', models.FloatField(blank=True, default=0, null=True)),
                ('recommandation', models.CharField(default='', max_length=10, null=True)),
                ('profit', models.FloatField(default=0, null=True)),
                ('return_ratio', models.FloatField(default=0, null=True)),
                ('volatility', models.FloatField(default=0, null=True)),
                ('evaluated', models.FloatField(default=0, null=True)),
                ('buy_dates', models.CharField(max_length=200, null=True)),
                ('sell_dates', models.CharField(max_length=200, null=True)),
                ('profit_history', models.CharField(max_length=200, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_port', to='portfolio.portfolio')),
            ],
        ),
    ]
