# Generated by Django 4.0.2 on 2022-12-10 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('buy_price', models.FloatField(default=0.0)),
                ('current_price', models.FloatField(default=0, null=True)),
                ('profit', models.FloatField(default=0, null=True)),
                ('return_ratio', models.FloatField(default=0, null=True)),
                ('volatility', models.FloatField(default=0, null=True)),
                ('evaluated', models.FloatField(default=0, null=True)),
                ('buy_dates', models.CharField(max_length=200, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_port', to='portfolio.portfolio')),
            ],
        ),
    ]
