# Generated by Django 4.1.4 on 2022-12-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='target_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
