# Generated by Django 4.0.5 on 2022-12-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_stock_target_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='port_value',
            field=models.FloatField(default=0, null=True),
        ),
    ]
