# Generated by Django 4.0.2 on 2022-12-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_delete_portpolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='stocks',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('buy_price', models.IntegerField(default=0)),
                ('add_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_port', to='portfolio.portfolio')),
            ],
        ),
    ]
