# Generated by Django 4.0.5 on 2022-12-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_port_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='port_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
