# Generated by Django 4.0.2 on 2022-12-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_add_port_stock_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='profit',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='return_ratio',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volatility',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
    ]
