# Generated by Django 4.0.2 on 2022-12-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_stock_current_price_stock_profit_stock_return_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='evaluated',
            field=models.FloatField(default=0, null=True),
        ),
    ]
