# Generated by Django 4.0.5 on 2022-12-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_transaction_alter_portfolio_monthly_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='money',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sell_dates',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sell_price',
            field=models.FloatField(default=0.0),
        ),
    ]
