# Generated by Django 4.0.2 on 2022-12-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_stock_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='buy_dates',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
