# Generated by Django 4.0.5 on 2022-12-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio_money_stock_sell_dates_stock_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='weight',
            field=models.FloatField(default=0, null=True),
        ),
    ]
