# Generated by Django 4.0.5 on 2022-12-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_portfolio_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='weight',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
