# Generated by Django 4.0.5 on 2022-12-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_portfolio_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_port', to='portfolio.portfolio'),
        ),
    ]
