# Generated by Django 4.0.5 on 2022-12-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_transaction_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='portfolio',
            new_name='trans_portfolio',
        ),
    ]
