# Generated by Django 4.0.5 on 2022-12-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_rename_portfolio_transaction_trans_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='curr_month_return',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='prev_month_return',
            field=models.FloatField(default=0, null=True),
        ),
    ]
