# Generated by Django 4.0.5 on 2022-12-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_stock_curr_month_return_stock_prev_month_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='curr_month',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='prev_month',
            field=models.TextField(default='', null=True),
        ),
    ]
