# Generated by Django 4.0.5 on 2022-12-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_stock_curr_month_stock_prev_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='curr_month',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='curr_month_return',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='prev_month',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='prev_month_return',
        ),
        migrations.AddField(
            model_name='stock',
            name='profit_hostory',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
