# Generated by Django 4.0.5 on 2022-12-30 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_stock_curr_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='profit_hostory',
            new_name='profit_history',
        ),
    ]
