# Generated by Django 4.0.5 on 2023-01-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_rename_profit_hostory_stock_profit_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='recommandation',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
