# Generated by Django 4.0.2 on 2022-12-10 03:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
