# Generated by Django 4.0.2 on 2022-12-10 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0007_remove_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='voter',
            field=models.ManyToManyField(default=None, related_name='voter_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
